BASEPROGRAM=isq
MPIBLASTPROGRAM=mpiblast
TESTPROGRAM=testisq
SETUPPROGRAM=setupdb

COMMONSOURCEFILESCPP=nwaln.cpp swaln.cpp 
COMMONSOURCEFILESCC=gbfp.c
GTESTSOURCEFILES=gtest/gtest-all.cc
BASESOURCEFILE=genISeqs.cpp
TESTSOURCEFILE=gbfpTest.cpp
SETUPSOURCEFILE=TransDBBuild.cpp
MPIBLASTSOURCEFILE=mpiblast.cpp


COMMONOBJFILESCPP=$(COMMONSOURCEFILESCPP:%.cpp=%.o)
COMMONOBJFILESCC=$(COMMONSOURCEFILESCC:%.c=%.o)
GTESTOBJECTFILE=$(GTESTSOURCEFILES:%.cc=%.o)
BASEOBJECTFILE=$(BASESOURCEFILE:%.cpp=%.o)
TESTOBJECTFILE=$(TESTSOURCEFILE:%.cpp=%.o)
SETUPOBJECTFILE=$(SETUPSOURCEFILE:%.cpp=%.o)
MPIBLASTOBJECTFILE=mpiblast.o

MPIEXISTCHECK := $(shell mpic++ --version 2>/dev/null)

all: target

.SUFFIXES: .c .cc .cpp .o

.c.o:
	gcc -g -c $<
.cpp.o:
	g++ -g -c $<
.cc.o:
	g++ -g -c -lpthread $<
	
MoveObjFiles: $(COMMONOBJFILESCPP) $(COMMONOBJFILESCC) $(TESTOBJECTFILE) $(GTESTOBJECTFILE)
	cp gtest-all.o gtest
	
CompileMPIBLAST:
ifdef MPIEXISTCHECK
	mpic++ -g -c $(MPIBLASTSOURCEFILE)
else
	@echo MPI compiler not found.
endif

$(BASEPROGRAM): $(COMMONOBJFILESCPP) $(COMMONOBJFILESCC) $(BASEOBJECTFILE)
	g++ -o $(BASEPROGRAM) $(COMMONOBJFILESCPP) $(COMMONOBJFILESCC) $(BASEOBJECTFILE)
	
$(MPIBLASTPROGRAM): CompileMPIBLAST
ifdef MPIEXISTCHECK
	mpic++ -o $(MPIBLASTPROGRAM) $(MPIBLASTOBJECTFILE)
else
	@echo MPI program not built.
endif

$(TESTPROGRAM): $(COMMONOBJFILESCPP) $(COMMONOBJFILESCC) $(TESTOBJECTFILE) MoveObjFiles $(GTESTOBJECTFILE) 
	g++ -o $(TESTPROGRAM) $(COMMONOBJFILESCPP) $(COMMONOBJFILESCC) $(TESTOBJECTFILE) $(GTESTOBJECTFILE) -lpthread

$(SETUPPROGRAM): $(COMMONOBJFILESCPP) $(COMMONOBJFILESCC) $(SETUPOBJECTFILE)
	g++ -o $(SETUPPROGRAM) $(COMMONOBJFILESCPP) $(COMMONOBJFILESCC) $(SETUPOBJECTFILE)
	
RunTest: $(TESTPROGRAM)
	./testisq	

target: $(SETUPPROGRAM) $(TESTPROGRAM) RunTest $(BASEPROGRAM) $(MPIBLASTPROGRAM)

clean : 
	rm *.o gtest/*.o $(BASEPROGRAM) $(TESTPROGRAM) $(SETUPPROGRAM) $(MPIBLASTPROGRAM)
	
